#!/usr/bin/env python3
"""Render the Codex binding surface from the live Claude Code tier.

Law enforced: `guide/general/harness-adapter.md` §4 (one source, two renderers) and §5 (what
each generated file carries). The body of the genome — `.agent-workspace/**` — is identical on
both harnesses and is never touched here.

Three source -> target pairs, and nothing else is generated:

    CLAUDE.md                        ->  AGENTS.md
    .claude/skills/<n>/SKILL.md      ->  .agents/skills/<n>/SKILL.md      (routing stub)
    .claude/agents/<n>.md            ->  .codex/agents/<n>.toml           (routing stub)

The units of the two sides are named before they are compared (`verification-gate-design.md`
§1): one SOURCE is one live capability file that Claude Code loads; one TARGET is one file the
Codex harness looks for by name. The mapping is one-to-one, so the comparison is over the same
kind of thing on both sides.

Both directions are checked (`verification-gate-design.md` §2):
  - nothing MISSING — every source has a target, and the target matches what the source renders
  - nothing EXTRA   — every generated file under the Codex surface maps back to a live source;
                      a source that was deleted leaves an orphan, and the orphan is reported
                      (`--check`) or removed (apply)

Usage: python .agent-workspace/tooling/render_codex.py [--check] [--quiet]
Exit:  0 = surface is current (or was written) · 1 = drift found (--check) · 2 = setup error
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8", errors="replace")

# Codex stops adding files to the instruction chain at `project_doc_max_bytes`; the default is
# 32 KiB and the overflow is dropped silently (`harness-adapter.md` §3.1).
DOC_MAX_BYTES = 32768

MARKER = "generated by .agent-workspace/tooling/render_codex.py"

CLAUDE_MD = "CLAUDE.md"
AGENTS_MD = "AGENTS.md"
RULES_DIR = ".claude/rules"
SKILLS_SRC = ".claude/skills"
SKILLS_DST = ".agents/skills"
AGENTS_SRC = ".claude/agents"
AGENTS_DST = ".codex/agents"

FM_KEY = re.compile(r"^([A-Za-z_][A-Za-z0-9_-]*):\s*(.*)$")


# ---------------------------------------------------------------- frontmatter


def parse_frontmatter(text: str) -> dict[str, str]:
    """Read the leading `---` block as flat key -> single-line value.

    A value wrapped onto following indented lines is joined with a single space, which is how
    every frontmatter field the genome uses is meant to read. Nothing else is interpreted: this
    is a field reader, not a YAML parser, and a file needing more than that is a file this
    renderer should not be guessing at.
    """
    lines = text.split("\n")
    if not lines or lines[0].strip() != "---":
        return {}
    out: dict[str, str] = {}
    key = None
    for line in lines[1:]:
        if line.strip() == "---":
            break
        m = FM_KEY.match(line)
        if m:
            key = m.group(1)
            out[key] = m.group(2).strip()
        elif key and line.startswith((" ", "\t")) and line.strip():
            out[key] = (out[key] + " " + line.strip()).strip()
    return out


def _first_line(s: str) -> str:
    return " ".join(s.split())


# ---------------------------------------------------------------- rule tier


def rule_tiers(root: Path) -> tuple[list[Path], list[Path]]:
    """Split the rule tier into (always-loaded, path-scoped).

    A rule with no `paths:` frontmatter is the always-loaded tier on Claude Code, and is exactly
    what Codex does NOT load on its own (`harness-adapter.md` §3.1) — so it is what the rendered
    header must name.
    """
    d = root / RULES_DIR
    if not d.is_dir():
        return [], []
    always, scoped = [], []
    for p in sorted(d.glob("*.md")):
        fm = parse_frontmatter(p.read_text(encoding="utf-8"))
        (scoped if "paths" in fm else always).append(p)
    return always, scoped


def rule_note(path: Path) -> str:
    """The `scope:` line of the rule's `<critical>` block, used as its one-line label."""
    for line in path.read_text(encoding="utf-8").split("\n")[:20]:
        if line.startswith("scope:") and not line.startswith("scope: portable") \
                and not line.startswith("scope: project"):
            return _first_line(line[len("scope:"):])
        if line.startswith(("target:", "core:")):
            return _first_line(line.split(":", 1)[1])
    return ""


# ---------------------------------------------------------------- renderers


def render_agents_md(root: Path) -> str:
    src = root / CLAUDE_MD
    body = src.read_text(encoding="utf-8")
    always, scoped = rule_tiers(root)

    out = [
        f"<!-- {MARKER} from {CLAUDE_MD} — do not edit; edit {CLAUDE_MD} and re-render -->",
        "",
        "## codex load note",
        "",
        "Codex does not auto-load `.claude/rules/`. This file is the whole always-loaded",
        "surface, so the rule tier is reached by reading it (`.agent-workspace/guide/general/harness-adapter.md` §3.1).",
        "",
        "read before the first substantive step of any task:",
    ]
    for p in always:
        note = rule_note(p)
        out.append(f"- `{p.relative_to(root).as_posix()}`" + (f" — {note}" if note else ""))
    if not always:
        out.append("- _(none)_")
    out += [
        "",
        "read when about to edit a file the rule names in its `paths:` frontmatter",
        "(on Codex the scoping is yours to apply — `harness-adapter.md` §3.2):",
    ]
    for p in scoped:
        note = rule_note(p)
        out.append(f"- `{p.relative_to(root).as_posix()}`" + (f" — {note}" if note else ""))
    if not scoped:
        out.append("- _(none)_")
    out += ["", "---", ""]
    return "\n".join(out) + body


def render_skill_stub(src: Path, name: str, rel: str | None = None) -> str:
    """`src` is opened; `rel` is the repo-relative path written into the stub's pointer."""
    rel = rel or src.as_posix()
    fm = parse_frontmatter(src.read_text(encoding="utf-8"))
    desc = _first_line(fm.get("description", ""))
    return (
        "---\n"
        f"name: {fm.get('name', name)}\n"
        f"description: {desc}\n"
        "---\n"
        "\n"
        f"<!-- {MARKER} from {rel} — do not edit; edit the source and re-render -->\n"
        "\n"
        f"Read `{rel}` and follow it exactly. That file is the single source of this\n"
        "skill's instructions; this stub exists only so Codex can find and route to it\n"
        "(`.agent-workspace/guide/general/harness-adapter.md` §5).\n"
    )


def _toml_str(s: str) -> str:
    return '"' + _first_line(s).replace("\\", "\\\\").replace('"', '\\"') + '"'


def render_agent_stub(src: Path, name: str, rel: str | None = None) -> str:
    """`src` is opened; `rel` is the repo-relative path written into the definition."""
    rel = rel or src.as_posix()
    fm = parse_frontmatter(src.read_text(encoding="utf-8"))
    return (
        f"# {MARKER} from {rel} — do not edit; edit the source and re-render\n"
        f"name = {_toml_str(fm.get('name', name))}\n"
        f"description = {_toml_str(fm.get('description', ''))}\n"
        "developer_instructions = \"\"\"\n"
        f"Read `{rel}` and follow it exactly. That file is the single source of this\n"
        "agent's instructions; this definition exists only so Codex can spawn it\n"
        "(`.agent-workspace/guide/general/harness-adapter.md` §5).\n"
        "\"\"\"\n"
    )


# ---------------------------------------------------------------- plan


def plan(root: Path) -> dict[str, str]:
    """target path (posix, repo-relative) -> the content it must hold."""
    targets: dict[str, str] = {}
    if (root / CLAUDE_MD).is_file():
        targets[AGENTS_MD] = render_agents_md(root)

    sk = root / SKILLS_SRC
    if sk.is_dir():
        for d in sorted(p for p in sk.iterdir() if p.is_dir()):
            src = d / "SKILL.md"
            if src.is_file():
                targets[f"{SKILLS_DST}/{d.name}/SKILL.md"] = render_skill_stub(
                    src, d.name, src.relative_to(root).as_posix())

    ag = root / AGENTS_SRC
    if ag.is_dir():
        for src in sorted(ag.glob("*.md")):
            targets[f"{AGENTS_DST}/{src.stem}.toml"] = render_agent_stub(
                src, src.stem, src.relative_to(root).as_posix())
    return targets


def existing_generated(root: Path) -> set[str]:
    """Every file currently sitting on the Codex surface that this renderer owns."""
    found: set[str] = set()
    if (root / AGENTS_MD).is_file():
        found.add(AGENTS_MD)
    for pat, base in ((f"{SKILLS_DST}/*/SKILL.md", SKILLS_DST), (f"{AGENTS_DST}/*.toml", AGENTS_DST)):
        if (root / base).is_dir():
            found.update(p.relative_to(root).as_posix() for p in root.glob(pat))
    return found


# ---------------------------------------------------------------- gate


def check_tree(root: Path) -> list[str]:
    problems: list[str] = []
    if not (root / CLAUDE_MD).is_file():
        return [f"{CLAUDE_MD} not found — nothing to render from"]

    want = plan(root)
    have = existing_generated(root)

    # direction 1: nothing MISSING
    for rel, content in want.items():
        p = root / rel
        if not p.is_file():
            problems.append(f"missing: {rel} — source changed or was never rendered")
        elif p.read_text(encoding="utf-8") != content:
            problems.append(f"stale: {rel} — does not match what its source renders")

    # direction 2: nothing EXTRA
    for rel in sorted(have - set(want)):
        problems.append(f"orphan: {rel} — no live source renders it")

    # the platform's own cap, counted in bytes
    n = len(want.get(AGENTS_MD, "").encode("utf-8"))
    if n >= DOC_MAX_BYTES:
        problems.append(
            f"{AGENTS_MD}: {n} bytes — Codex project_doc_max_bytes is {DOC_MAX_BYTES}; "
            "the overflow is dropped silently (harness-adapter.md §3.1)")
    return problems


def apply_tree(root: Path) -> list[str]:
    want = plan(root)
    have = existing_generated(root)
    actions: list[str] = []
    for rel, content in sorted(want.items()):
        p = root / rel
        current = p.read_text(encoding="utf-8") if p.is_file() else None
        if current == content:
            continue
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(content, encoding="utf-8", newline="\n")
        actions.append(("write " if current is None else "update ") + rel)
    for rel in sorted(have - set(want)):
        p = root / rel
        p.unlink()
        # a skill stub owns its own directory; drop it once it is empty, but never climb past
        # the surface roots themselves
        parent = p.parent
        if parent != root / SKILLS_DST and parent != root / AGENTS_DST and parent != root \
                and not any(parent.iterdir()):
            parent.rmdir()
        actions.append("remove " + rel)
    return actions


def main() -> int:
    quiet = "--quiet" in sys.argv
    root = Path(".").resolve()
    if not (root / CLAUDE_MD).is_file():
        print(f"render_codex: {CLAUDE_MD} not found — run from the project root", file=sys.stderr)
        return 2

    if "--check" in sys.argv:
        problems = check_tree(root)
        if problems:
            print("render_codex --check: Codex surface is out of date")
            for p in problems:
                print("  -", p)
            print("  fix: python .agent-workspace/tooling/render_codex.py")
            return 1
        if not quiet:
            n = len(plan(root).get(AGENTS_MD, "").encode("utf-8"))
            print(f"render_codex --check: current · {AGENTS_MD} {n}/{DOC_MAX_BYTES} bytes")
        return 0

    actions = apply_tree(root)
    if not quiet:
        print(f"render_codex: {len(actions)} change(s)")
        for a in actions:
            print("  ", a)
    return 0


if __name__ == "__main__":
    sys.exit(main())
