#!/usr/bin/env python3
"""Render the Codex platform set from the authored Claude Code set.

Law enforced: `guide/general/harness-adapter.md`. The two platform sets are peers and neither
may name a path belonging to the other; the shared body `.agent-workspace/**` is identical for
both and is never touched here.

Source -> target, and nothing else is generated:

    CLAUDE.md                    ->  AGENTS.md            root index + the always-loaded tier inlined
    .claude/rules/<n>.md         ->  .codex/rules/<n>.md  the rule tier, path-rewritten
    .claude/skills/<n>/SKILL.md  ->  .agents/skills/<n>/SKILL.md   full body, per the Codex manual
    .claude/agents/<n>.md        ->  .codex/agents/<n>.toml        full body in developer_instructions
    (composed)                   ->  .codex/config.toml   project_doc_max_bytes for the chain

Paths are the ones the shipped Codex manual states: repo skills are scanned from `.agents/skills`
(manual line 21982 and the scope table), subagents are TOML under `.codex/agents/`, and the
instruction chain is `AGENTS.md` capped by `project_doc_max_bytes` (manual 22756).

`.codex/rules/*.md` is deliberately `.md`: the execpolicy engine loads `.rules` files, so markdown
there is inert to it (manual 28973, 29097, 15257). Prose must never be written to a `.rules` file.

Units, named before comparison (`verification-gate-design.md` §1): one SOURCE is one authored file
of the Claude Code set; one TARGET is one file the Codex platform reads. The map is one-to-one
except `AGENTS.md` and `.codex/config.toml`, which are composed from several sources.

Both directions are checked (`verification-gate-design.md` §2): nothing MISSING (every source has
its target, matching byte for byte) and nothing EXTRA (every generated file maps back to a live
source; a deleted source leaves an orphan that is reported or removed). A third check has no
direction — no generated file may mention the other platform.

Usage: python .agent-workspace/tooling/render_codex.py [--check] [--quiet]
Exit:  0 = current (or written) · 1 = drift found (--check) · 2 = setup error
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8", errors="replace")

MARKER = "generated by .agent-workspace/tooling/render_codex.py"

CLAUDE_MD = "CLAUDE.md"
AGENTS_MD = "AGENTS.md"
RULES_SRC = ".claude/rules"
RULES_DST = ".codex/rules"
SKILLS_SRC = ".claude/skills"
SKILLS_DST = ".agents/skills"
AGENTS_SRC = ".claude/agents"
AGENTS_DST = ".codex/agents"
CODEX_CONFIG = ".codex/config.toml"

# Not mirrored: each of these describes a mechanism that exists only on the Claude Code side, and
# a path rewrite cannot make it true elsewhere. `claude-md-standards.md` governs a file the Codex
# set does not have; `subagent-standards.md` describes a markdown agent file with frontmatter,
# spawned through that platform's own tool — the Codex side defines agents as TOML with different
# fields, so the Codex set needs its own standard rather than a translation of this one.
RULES_NOT_MIRRORED = {"claude-md-standards.md", "subagent-standards.md"}

# Longest token first: `.claude/skills/` must win before `.claude/` would match.
REWRITES = [
    (".claude/skills/", f"{SKILLS_DST}/"),
    (".claude/agents/", f"{AGENTS_DST}/"),
    (".claude/rules/", f"{RULES_DST}/"),
    (".claude/", ".codex/"),
    ("CLAUDE.md", AGENTS_MD),
    # a standard that exists on both sides under its own platform name
    ("claude-md-standards.md", "agents-md-standards.md"),
    ("subagent-standards.md", "codex-agents-standards.md"),
]

# `.claude-plugin/` is this repo's own Claude Code packaging — a fact about the repository, not a
# pointer into the other platform's genome set. It carries no slash after `.claude`, so neither the
# rewrites nor this pattern touch it. What IS forbidden is a generated file reaching into the
# Claude Code set: `.claude/<anything>` or the name of its root index.
LEAK = re.compile(r"\.claude/|CLAUDE\.md")

FM_KEY = re.compile(r"^([A-Za-z_][A-Za-z0-9_-]*):\s*(.*)$")


def rewrite(text: str) -> str:
    for a, b in REWRITES:
        text = text.replace(a, b)
    return text


def parse_frontmatter(text: str) -> dict[str, str]:
    """Read the leading `---` block as flat key -> single-line value.

    A value wrapped onto following indented lines is joined with one space. Nothing else is
    interpreted: this is a field reader, not a YAML parser, and a file needing more than that is
    a file this renderer should not be guessing at.
    """
    lines = text.split("\n")
    if not lines or lines[0].strip() != "---":
        return {}
    out: dict[str, str] = {}
    key = None
    for line in lines[1:]:
        if line.strip() == "---":
            break
        m = FM_KEY.match(line)
        if m:
            key = m.group(1)
            out[key] = m.group(2).strip()
        elif key and line.startswith((" ", "\t")) and line.strip():
            out[key] = (out[key] + " " + line.strip()).strip()
    return out


def strip_frontmatter(text: str) -> str:
    lines = text.split("\n")
    if not lines or lines[0].strip() != "---":
        return text
    for i, line in enumerate(lines[1:], start=1):
        if line.strip() == "---":
            return "\n".join(lines[i + 1:]).lstrip("\n")
    return text


def _one_line(s: str) -> str:
    s = " ".join(s.split())
    # a folded/literal YAML scalar marker (`>`, `|`) introduces the value, it is not in it
    return s[1:].strip() if s[:1] in (">", "|") else s


GLOB = re.compile(r'^\s*-\s*"([^"]+)"', re.M)


def paths_globs(text: str) -> list[str]:
    """The quoted globs of a rule's `paths:` block, in order.

    Read from the raw frontmatter rather than the flattened field: the value is a YAML list,
    and flattening it to one string loses the item boundaries a trigger line needs.
    """
    lines = text.split("\n")
    if not lines or lines[0].strip() != "---":
        return []
    block, seen = [], False
    for line in lines[1:]:
        if line.strip() == "---":
            break
        if line.startswith("paths:"):
            seen = True
            continue
        if seen:
            if line.startswith((" ", "\t")):
                block.append(line)
            else:
                break
    return GLOB.findall("\n".join(block))


# ---------------------------------------------------------------- rule tier


def mirrored_rules(root: Path) -> list[Path]:
    d = root / RULES_SRC
    if not d.is_dir():
        return []
    return [p for p in sorted(d.glob("*.md")) if p.name not in RULES_NOT_MIRRORED]


def codex_rules(root: Path) -> list[tuple[str, str]]:
    """(file name, final text) of every rule the Codex set carries.

    Two origins, one tier: a mirror of a shared rule, already path-rewritten, and a rule authored
    for this platform alone. The composer must see both or the platform-only ones would have no
    trigger line and never be reached.
    """
    out = [(p.name, rewrite(p.read_text(encoding="utf-8"))) for p in mirrored_rules(root)]
    d = root / RULES_DST
    if d.is_dir():
        for p in sorted(d.glob("*.md")):
            text = p.read_text(encoding="utf-8")
            if MARKER not in text.split("\n", 1)[0]:
                out.append((p.name, text))
    return sorted(out)


def split_tiers(root: Path) -> tuple[list[tuple[str, str]], list[tuple[str, str]]]:
    """(always-loaded, path-scoped).

    A rule with no `paths:` frontmatter is one the other platform loads every turn. Codex has no
    second auto-load tier, so that set is what `AGENTS.md` must carry inline.
    """
    always, scoped = [], []
    for name, text in codex_rules(root):
        (scoped if "paths" in parse_frontmatter(text) else always).append((name, text))
    return always, scoped


def rule_note(text: str) -> str:
    for line in text.split("\n")[:20]:
        if line.startswith("scope:") and line.strip() not in ("scope: portable", "scope: project"):
            return _one_line(line[len("scope:"):])
        if line.startswith(("target:", "core:")):
            return _one_line(line.split(":", 1)[1])
    return ""


# ---------------------------------------------------------------- renderers


def render_rule(src_text: str) -> str:
    return f"<!-- {MARKER} — do not edit; regenerate instead -->\n" + rewrite(src_text)


def render_agents_md(root: Path) -> str:
    always, scoped = split_tiers(root)
    out = [f"<!-- {MARKER} — do not edit; regenerate instead -->", ""]
    out.append(rewrite((root / CLAUDE_MD).read_text(encoding="utf-8")).rstrip("\n"))

    if scoped:
        out += ["", "## file-type standards", "",
                "Codex scopes instructions by working directory, not by the file being edited, so",
                "these are reached by their trigger rather than loaded automatically:", ""]
        for name, text in scoped:
            globs = paths_globs(text)
            where = " / ".join(f"`{g}`" for g in globs) if globs else "a matching file"
            note = rule_note(text)
            out.append(f"- about to edit {where} → MUST Read `{RULES_DST}/{name}`"
                       + (f" — {note}" if note else ""))

    if always:
        out += ["", "---", "",
                "# always-loaded rules",
                "",
                "Codex has no rule tier that loads on its own, so the tier is carried here in full.",
                "Each section below is the complete text of one rule file; the file itself is the",
                f"editable copy under `{RULES_DST}/`."]
        for name, text in always:
            out += ["", "---", "", f"## rule: {name}", "", strip_frontmatter(text).rstrip("\n")]
    return "\n".join(out) + "\n"


def render_codex_config(agents_md: str) -> str:
    """`project_doc_max_bytes` sized to the chain this render actually produces.

    Manual 22756: Codex stops adding files once the combined size reaches the limit, and the
    overflow is dropped without a warning. Manual 12146 lists every key a project config may not
    override and this is not one of them, so a repo may ship it.
    """
    need = len(agents_md.encode("utf-8"))
    # round up to the next 64 KiB so ordinary edits do not move the number every commit
    block = 65536
    limit = max(block, ((need // block) + 1) * block)
    return (f"# {MARKER} — do not edit; regenerate instead\n"
            "#\n"
            "# The instruction chain is capped by project_doc_max_bytes and the overflow is\n"
            "# dropped silently, so the cap is sized to the rendered AGENTS.md with headroom.\n"
            f"# rendered AGENTS.md: {need} bytes\n"
            "#\n"
            "# Project config loads only when the project is trusted.\n"
            f"project_doc_max_bytes = {limit}\n")


def render_skill(src_text: str, name: str) -> str:
    fm = parse_frontmatter(src_text)
    body = strip_frontmatter(src_text).rstrip("\n")
    return ("---\n"
            f"name: {fm.get('name', name)}\n"
            f"description: {rewrite(_one_line(fm.get('description', '')))}\n"
            "---\n"
            "\n"
            f"<!-- {MARKER} — do not edit; regenerate instead -->\n"
            "\n"
            + rewrite(body) + "\n")


def _toml_basic(s: str) -> str:
    return '"' + _one_line(s).replace("\\", "\\\\").replace('"', '\\"') + '"'


def _toml_multiline(s: str) -> str:
    # A basic multi-line string ends at `"""`, and a trailing quote would glue onto it.
    return '"""\n' + s.replace("\\", "\\\\").replace('"""', '\\"\\"\\"').rstrip("\n") + '\n"""'


def render_agent(src_text: str, name: str) -> str:
    fm = parse_frontmatter(src_text)
    body = strip_frontmatter(src_text).rstrip("\n")
    return (f"# {MARKER} — do not edit; regenerate instead\n"
            f"name = {_toml_basic(fm.get('name', name))}\n"
            f"description = {_toml_basic(rewrite(fm.get('description', '')))}\n"
            f"developer_instructions = {_toml_multiline(rewrite(body))}\n")


# ---------------------------------------------------------------- plan


def plan(root: Path) -> dict[str, str]:
    """target path (posix, repo-relative) -> the content it must hold."""
    targets: dict[str, str] = {}
    if not (root / CLAUDE_MD).is_file():
        return targets

    for p in mirrored_rules(root):
        targets[f"{RULES_DST}/{p.name}"] = render_rule(p.read_text(encoding="utf-8"))

    agents_md = render_agents_md(root)
    targets[AGENTS_MD] = agents_md
    targets[CODEX_CONFIG] = render_codex_config(agents_md)

    sk = root / SKILLS_SRC
    if sk.is_dir():
        for d in sorted(x for x in sk.iterdir() if x.is_dir()):
            src = d / "SKILL.md"
            if src.is_file():
                targets[f"{SKILLS_DST}/{d.name}/SKILL.md"] = render_skill(
                    src.read_text(encoding="utf-8"), d.name)

    ag = root / AGENTS_SRC
    if ag.is_dir():
        for src in sorted(ag.glob("*.md")):
            targets[f"{AGENTS_DST}/{src.stem}.toml"] = render_agent(
                src.read_text(encoding="utf-8"), src.stem)
    return targets


def existing_generated(root: Path) -> set[str]:
    found: set[str] = set()
    for rel in (AGENTS_MD, CODEX_CONFIG):
        if (root / rel).is_file():
            found.add(rel)
    for pat, base in ((f"{SKILLS_DST}/*/SKILL.md", SKILLS_DST),
                      (f"{AGENTS_DST}/*.toml", AGENTS_DST)):
        if (root / base).is_dir():
            found.update(p.relative_to(root).as_posix() for p in root.glob(pat))
    # `.codex/rules/` mixes generated mirrors with rules authored for this platform alone. The
    # marker is what tells them apart: a file without it is somebody's work, not this tool's
    # output, and deleting it as an orphan would be the renderer eating hand-written law.
    d = root / RULES_DST
    if d.is_dir():
        for p in sorted(d.glob("*.md")):
            head = p.read_text(encoding="utf-8").split("\n", 1)[0]
            if MARKER in head:
                found.add(p.relative_to(root).as_posix())
    return found


# ---------------------------------------------------------------- gate


def leaks(rel: str, content: str) -> list[str]:
    """Lines reaching outside the Codex set.

    Two ways to reach out, and both are dead references from inside a deployed Codex project:
    naming a path of the other platform, and naming a rule file this set deliberately does not
    carry (`RULES_NOT_MIRRORED`) — the pointer resolves on the other side only.
    """
    out = []
    for i, line in enumerate(content.split("\n"), start=1):
        if LEAK.search(line):
            out.append(f"cross-reference: {rel}:{i} names the Claude Code set — {line.strip()[:80]}")
        for name in RULES_NOT_MIRRORED:
            if name in line:
                out.append(f"dangling: {rel}:{i} names `{name}`, which this set does not carry "
                           f"— {line.strip()[:70]}")
    return out


def check_tree(root: Path) -> list[str]:
    if not (root / CLAUDE_MD).is_file():
        return [f"{CLAUDE_MD} not found — nothing to render from"]

    problems: list[str] = []
    want = plan(root)
    have = existing_generated(root)

    for rel, content in want.items():
        p = root / rel
        if not p.is_file():
            problems.append(f"missing: {rel} — source changed or was never rendered")
        elif p.read_text(encoding="utf-8") != content:
            problems.append(f"stale: {rel} — does not match what its source renders")
        problems += leaks(rel, content)

    for rel in sorted(have - set(want)):
        problems.append(f"orphan: {rel} — no live source renders it")

    n = len(want.get(AGENTS_MD, "").encode("utf-8"))
    limit = 0
    m = re.search(r"project_doc_max_bytes = (\d+)", want.get(CODEX_CONFIG, ""))
    if m:
        limit = int(m.group(1))
    if n >= limit:
        problems.append(f"{AGENTS_MD}: {n} bytes >= the {limit} the rendered config declares")
    return problems


def apply_tree(root: Path) -> list[str]:
    want = plan(root)
    have = existing_generated(root)
    actions: list[str] = []
    for rel, content in sorted(want.items()):
        p = root / rel
        current = p.read_text(encoding="utf-8") if p.is_file() else None
        if current == content:
            continue
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(content, encoding="utf-8", newline="\n")
        actions.append(("write " if current is None else "update ") + rel)
    roots = {root / RULES_DST, root / SKILLS_DST, root / AGENTS_DST, root}
    for rel in sorted(have - set(want)):
        p = root / rel
        p.unlink()
        if p.parent not in roots and not any(p.parent.iterdir()):
            p.parent.rmdir()
        actions.append("remove " + rel)
    return actions


def main() -> int:
    quiet = "--quiet" in sys.argv
    root = Path(".").resolve()
    if not (root / CLAUDE_MD).is_file():
        print(f"render_codex: {CLAUDE_MD} not found — run from the project root", file=sys.stderr)
        return 2

    if "--check" in sys.argv:
        problems = check_tree(root)
        if problems:
            print("render_codex --check: the Codex set is out of date")
            for p in problems:
                print("  -", p)
            print("  fix: python .agent-workspace/tooling/render_codex.py")
            return 1
        if not quiet:
            want = plan(root)
            n = len(want.get(AGENTS_MD, "").encode("utf-8"))
            m = re.search(r"project_doc_max_bytes = (\d+)", want.get(CODEX_CONFIG, ""))
            print(f"render_codex --check: current · {len(want)} files · "
                  f"{AGENTS_MD} {n}/{m.group(1) if m else '?'} bytes")
        return 0

    actions = apply_tree(root)
    if not quiet:
        print(f"render_codex: {len(actions)} change(s)")
        for a in actions:
            print("  ", a)
    return 0


if __name__ == "__main__":
    sys.exit(main())
